### ISSUE TITLE
404 on certain tools/toys

### ISSUE THREAD

**Issue by from-nibly** [KeJunMao/vscode-devtoys#1]
The following toys show blank screens and are met with a 404 error in the dev console

URL Encoder
Hash Generator
Regex Tester
Color Blindness Simulator

OS NixOS 21.11 (Linux) 5.10.96
VSCode Version 1.64.0
Extension version 0.0.9

Error looks like this

```
GET https://file+.vscode-resource.vscode-webview.net/home/jordan/.vscode/extensions/kejun.devtoys-0.0.9/out/compiled/colorBlindnessSimulator.js net::ERR_ABORTED 404
```

**Comment by KeJunMao** [comment]
thank you report, it's a filename bug. can you try 0.0.10?

**Comment by from-nibly** [comment]
That worked thanks!
