### ISSUE TITLE
JWT disappears when input is cleared

### ISSUE THREAD

**Issue by KillDozerX2** [KeJunMao/vscode-devtoys#10]
https://user-images.githubusercontent.com/29596786/155538834-cfb66a32-1867-4c9f-8e90-a0a1a721d5dc.mov

**Comment by KeJunMao** [comment]
I can't reproduce it

**Comment by KeJunMao** [comment]
![image](https://user-images.githubusercontent.com/18414281/155656443-6d7d2ef7-5d03-4dc4-ae2b-68a8c780c729.png)
![image](https://user-images.githubusercontent.com/18414281/155656464-b25dbf2f-31e8-4603-9c76-43d5eb7ed852.png)

**Comment by KillDozerX2** [comment]
Maybe it's a macos thing?

**Comment by KeJunMao** [comment]
I’m used macos to

**Comment by KeJunMao** [comment]
Can you copy your dev console log here?
