### ISSUE TITLE
Latest version not on the market place yet

### ISSUE THREAD

**Issue by KillDozerX2** [KeJunMao/vscode-devtoys#4]
It seems that latest version is not on the marketplace yet as there was no demo section in the README.

**Comment by KeJunMao** [comment]
Thank you for your feedback. The new toy has not been developed yet. When it is ready, I will release it together!

**Comment by KillDozerX2** [comment]
Understood, do you need help setting up automated deployments?

**Comment by KeJunMao** [comment]
yeah,I want use `semantic-release` and github actions with vsce. do you have any experience

**Comment by KillDozerX2** [comment]
Yes, I'll try to send a pr soon.
