### ISSUE TITLE
about CI/CD

### ISSUE THREAD

**Issue by KeJunMao** [KeJunMao/vscode-devtoys#6]
@KillDozerX2 we can talk about CI/CD here

**Comment by KillDozerX2** [comment]
Sure, I am about to create a pr in the next 10 minutes if you wanna have a look.

**Comment by KeJunMao** [comment]
Just now I added @commitlint/cli and husky's commit-msg hooks

Are you going to use semantic-release, maybe we can also create .vsix files to release

**Comment by KillDozerX2** [comment]
Hey, yes using semantic release along with github actions. There are a few hiccups getting started but once setup, we no longer have to worry about it.

**Comment by KeJunMao** [comment]
added VSCE_PAT secret
why closed pr?

**Comment by KillDozerX2** [comment]
Because I don't link merge commits.

**Comment by KeJunMao** [comment]
Do you want to join collaborator?If you like, I invite you!

**Comment by KeJunMao** [comment]
your can review you pr,i'm not good for ci/cd jobs...

**Comment by KillDozerX2** [comment]
Sure, that would be nice

**Comment by KeJunMao** [comment]
ok,done welcome!😊

**Comment by KillDozerX2** [comment]
Solved, latest version on VSCode marketplace.
